#!/usr/bin/env ruby

# sample/build-ruby - build script for ruby
#
# Copyright (C) 2005-2013 Tanaka Akira  <akr@fsij.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#  3. The name of the author may not be used to endorse or promote
#     products derived from this software without specific prior
#     written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

require 'chkbuild'

#ENV['LC_ALL'] = 'C'

# resource limits
word_bytes = [nil].pack("p").length
ChkBuild.limit(:cpu => 3600*4) # seconds
ChkBuild.limit(:stack => 1024*1024*10*word_bytes) # bytes
ChkBuild.limit(:data => 1024*1024*500*word_bytes) # bytes
ChkBuild.limit(:as => 1024*1024*500*word_bytes) # bytes

# ChkBuild.nickname identify chkbuild installation.
# It is used for title of HTML, etc.
# The default is the hostname (without domain).
# ChkBuild.nickname = 'nickname'

# ChkBuild.top_uri is used for RSS.
# ChkBuild.top_uri = "file://#{ChkBuild.public_top}/"
ChkBuild.top_uri = nil # use relative URL

ChkBuild::Ruby.def_target(
  [
    { :suffix_? => '-trunk', :ruby_branch => 'trunk',               :output_interval_timeout => '10min' },
    { :suffix_? => '-2.1.0', :ruby_branch => 'branches/ruby_2_1',   :output_interval_timeout => '10min' },
    { :suffix_? => '-2.0.0', :ruby_branch => 'branches/ruby_2_0_0', :output_interval_timeout => '10min' },
    { :suffix_? => '-1.9.3', :ruby_branch => 'branches/ruby_1_9_3', :output_interval_timeout => '10min' },
  ],
  { :use_rubyspec => true },
  { :configure_args => [] },

  [
    { :suffix_? => '-m64',
      :optflags => '-march=corei7-avx -mtune=corei7-avx',
      :configure_args_arch => '--with-arch=x86_64',
      :configure_args_openssl => %W[--with-openssl-dir=/usr/local/opt/openssl], },
    #{ :suffix_? => '-m32',
    #  :optflags => '-march=i686 -mtune=i686',
    #  :configure_args_arch => '--with-arch=i386',
    #  :configure_args_openssl => %W[--with-openssl-dir=/usr/local/opt/openssl-m32], },
  ],

  [
    { :suffix_? => '-o3', :optflags => %w[-O3], },
    { :suffix_? => '-o0', :optflags => %w[-O0], },
  ],

  :configure_args_cc => %w[CC=clang],
  :configure_args_cxx => %w[CXX=clang++],
  :configure_args_valgrind => %w[--with-valgrind],
  :configure_args_db       => %w[--with-db-dir=/usr/local/opt/berkeley-db],
  :configure_args_dbm      => %w[--with-dbm-dir=/usr/local/opt/gdbm --with-dbm-type=gdbm],
  :configure_args_gdbm     => %w[--with-gdbm-dir=/usr/local/opt/gdbm],
  :configure_args_libyaml  => %w[--with-libyaml-dir=/usr/local/opt/libyaml],
  :configure_args_libffi   => %w[--with-libffi-dir=/usr/local/opt/libffi],
  :configure_args_readline => %w[--with-readline-dir=/usr/local/opt/readline --disable-libedit],
  :configure_args_others   => %w[--enable-shared --with-out-ext=tk,tk/*],

  :warnflags => %w[-W -Wall -Wformat=2 -Wundef -Wno-parentheses -Wno-unused-parameter -Wno-missing-field-initializers],
  :debugflags => '-ggdb3',

  :make_options => { 'main' => '-j8', },

  # :autoconf_command => 'autoconf',
  # :cppflags => %w[-DRUBY_DEBUG_ENV],
  # :dldflags => %w[],

  # :validate_dependencies => false,
  # :validate_dependencies => true,     # needs gmake and gcc 4.5 or later.
  #
  # :do_test => true,

  # :old => 1,

  :timeout => '1h',

  :output_interval_timeout => '10min'
  )

ChkBuild.main
